//! Stage 2: byte scanner.
//!
//! Walks the chunked save buffer with `memchr`. Detects `<info>`, `<game …>`,
//! `<player …>`, `<component class="sector" …>`, `<component …>`, and
//! `</component>` patterns. Produces:
//! - `SnapshotMeta` (from <info>)
//! - `FactionOverrides` (per-sector owner string)
//! - `Vec<SectorChunk>` (byte ranges of each top-level sector subtree)
//!
//! Does NOT touch ship/station entities — that happens in Stage 3.

use std::sync::mpsc::Receiver;

use map_domain::world::SnapshotMeta;
use memchr::memchr;
use memchr::memmem;

use super::types::{FactionOverrides, SectorChunk};

/// Find an attribute value inside a single XML start tag's bytes.
/// Returns the raw byte slice (without quotes).
///
/// Cheap and forgiving — assumes well-formed double-quoted attributes
/// generated by X4. Returns None if the attribute is absent.
pub(crate) fn find_attr<'a>(tag: &'a [u8], name: &[u8]) -> Option<&'a [u8]> {
    let mut needle: Vec<u8> = Vec::with_capacity(name.len() + 2);
    needle.extend_from_slice(name);
    needle.extend_from_slice(b"=\"");
    let start = memmem::find(tag, &needle)? + needle.len();
    let rest = &tag[start..];
    let end = memchr(b'"', rest)?;
    Some(&rest[..end])
}

/// What Stage 2 produces.
pub struct ScanOutput {
    pub meta: SnapshotMeta,
    pub overrides: FactionOverrides,
    pub chunks: Vec<SectorChunk>,
    pub bytes: Vec<u8>,
}

/// Drain `rx` and scan all bytes. Caller passes the source path + mtime so
/// `SnapshotMeta` can be filled out completely.
pub fn run_scan(
    rx: Receiver<Vec<u8>>,
    path: std::path::PathBuf,
    mtime: std::time::SystemTime,
) -> std::io::Result<ScanOutput> {
    let mut bytes: Vec<u8> = Vec::with_capacity(128 * 1024 * 1024);
    while let Ok(chunk) = rx.recv() {
        bytes.extend_from_slice(&chunk);
    }

    let mut meta = SnapshotMeta {
        path,
        mtime,
        game_time_seconds: 0.0,
        player_money: 0,
        player_location_name: String::new(),
        game_version: String::new(),
    };
    scan_info(&bytes, &mut meta);

    let (overrides, chunks) = scan_sectors(&bytes);

    Ok(ScanOutput {
        meta,
        overrides,
        chunks,
        bytes,
    })
}

/// Scan only the <info> region for game/player attrs. Cheap.
fn scan_info(bytes: &[u8], meta: &mut SnapshotMeta) {
    let info_end = memmem::find(bytes, b"</info>").unwrap_or(bytes.len());
    let region = &bytes[..info_end];

    if let Some(tag) = find_tag(region, b"<game ") {
        let ver = find_attr(tag, b"version").map(str_from).unwrap_or_default();
        let build = find_attr(tag, b"build").map(str_from).unwrap_or_default();
        meta.game_version = match (ver.is_empty(), build.is_empty()) {
            (false, false) => format!("{}.{}", ver, build),
            (false, true) => ver,
            (true, false) => build,
            _ => String::new(),
        };
        if let Some(t) = find_attr(tag, b"time").and_then(parse_f32) {
            meta.game_time_seconds = t;
        }
    }
    if let Some(tag) = find_tag(region, b"<player ") {
        if let Some(m) = find_attr(tag, b"money").and_then(parse_u64) {
            meta.player_money = m;
        }
        if let Some(loc) = find_attr(tag, b"location").map(str_from) {
            meta.player_location_name = loc;
        }
    }
}

/// Walk the buffer collecting sector chunks + faction overrides.
///
/// Strategy: scan all `<component …>` opens. When we hit one with
/// `class="sector"` and we're NOT already inside a sector, start tracking.
/// While tracking, count `<component …>` opens vs `</component>` closes
/// (starting at depth=1) until depth returns to 0 — that's the end of the
/// sector subtree.
fn scan_sectors(bytes: &[u8]) -> (FactionOverrides, Vec<SectorChunk>) {
    let mut overrides = FactionOverrides::new();
    let mut chunks: Vec<SectorChunk> = Vec::new();

    // State for the currently-open sector (None == not inside any sector).
    let mut sector_start: Option<usize> = None;
    let mut sector_macro: Option<String> = None;
    // Depth within the currently-tracked sector. Only meaningful when
    // sector_start.is_some().
    let mut depth: u32 = 0;

    // Trailing space prevents matching `<components>` (plural container tag).
    let open_needle: &[u8] = b"<component ";
    let close_needle: &[u8] = b"</component>";
    let close_finder = memmem::Finder::new(close_needle);
    let open_finder = memmem::Finder::new(open_needle);

    let mut pos = 0;
    while pos < bytes.len() {
        let next_open = open_finder.find(&bytes[pos..]).map(|i| i + pos);
        let next_close = close_finder.find(&bytes[pos..]).map(|i| i + pos);

        // Pick the earlier of the two events.
        let (event_pos, is_open) = match (next_open, next_close) {
            (None, None) => break,
            (Some(o), Some(c)) => {
                if o < c {
                    (o, true)
                } else {
                    (c, false)
                }
            }
            (Some(o), None) => (o, true),
            (None, Some(c)) => (c, false),
        };

        if is_open {
            // Read the full tag.
            let close_gt = match memchr(b'>', &bytes[event_pos..]) {
                Some(i) => event_pos + i,
                None => break,
            };
            let tag_end = close_gt + 1;
            let tag = &bytes[event_pos..tag_end];
            // Self-closing `<component .../>`: emits no `</component>`, so it
            // contributes zero net depth change.
            let self_closing = tag.len() >= 2 && tag[tag.len() - 2] == b'/';

            if sector_start.is_none() {
                // Not tracking anything; only care if this is a sector.
                if let Some(class) = find_attr(tag, b"class") {
                    if class == b"sector" && !self_closing {
                        let mac =
                            find_attr(tag, b"macro").map(str_from).unwrap_or_default();
                        let macro_lower = mac.to_lowercase();
                        if let Some(owner) = find_attr(tag, b"owner").map(str_from) {
                            overrides.insert(macro_lower.clone(), owner);
                        }
                        sector_start = Some(event_pos);
                        sector_macro = Some(macro_lower);
                        depth = 1;
                    }
                }
            } else if !self_closing {
                // Already inside a sector — just count nesting depth.
                depth += 1;
            }
            pos = tag_end;
        } else {
            // Close.
            pos = event_pos + close_needle.len();
            if sector_start.is_some() {
                depth -= 1;
                if depth == 0 {
                    if let (Some(start), Some(mac)) =
                        (sector_start.take(), sector_macro.take())
                    {
                        chunks.push(SectorChunk {
                            sector_macro: mac,
                            byte_range: start..pos,
                        });
                    }
                }
            }
        }
    }

    (overrides, chunks)
}

fn find_tag<'a>(haystack: &'a [u8], needle: &[u8]) -> Option<&'a [u8]> {
    let start = memmem::find(haystack, needle)?;
    let close = memchr(b'>', &haystack[start..])? + start;
    Some(&haystack[start..=close])
}

fn str_from(b: &[u8]) -> String {
    String::from_utf8_lossy(b).into_owned()
}

fn parse_f32(b: &[u8]) -> Option<f32> {
    std::str::from_utf8(b).ok()?.parse().ok()
}

fn parse_u64(b: &[u8]) -> Option<u64> {
    std::str::from_utf8(b).ok()?.parse().ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn find_attr_extracts_simple_value() {
        let tag = b"<component class=\"sector\" macro=\"foo_macro\" owner=\"argon\">";
        assert_eq!(find_attr(tag, b"class"), Some(b"sector".as_ref()));
        assert_eq!(find_attr(tag, b"macro"), Some(b"foo_macro".as_ref()));
        assert_eq!(find_attr(tag, b"owner"), Some(b"argon".as_ref()));
        assert_eq!(find_attr(tag, b"missing"), None);
    }

    #[test]
    fn scan_extracts_meta_overrides_and_one_chunk() {
        let payload: &[u8] = br#"<?xml version="1.0"?>
<savegame>
  <info>
    <game version="800" build="1" time="100.0"/>
    <player money="42" location="{20004,1}"/>
  </info>
  <universe>
    <component class="galaxy" macro="g">
      <component class="cluster" macro="c">
        <component class="sector" macro="SectorAMacro" owner="argon">
          <component class="ship_s" macro="ship_arg_s" id="[0x10]">
            <offset><position x="1" y="2" z="3"/></offset>
          </component>
        </component>
      </component>
    </component>
  </universe>
</savegame>"#;

        let (tx, rx) = std::sync::mpsc::sync_channel(8);
        tx.send(payload.to_vec()).unwrap();
        drop(tx);

        let out = run_scan(
            rx,
            std::path::PathBuf::from("/tmp/test_save.xml.gz"),
            std::time::UNIX_EPOCH,
        )
        .expect("scan ok");

        assert_eq!(out.meta.player_money, 42);
        assert_eq!(out.meta.game_version, "800.1");
        assert!((out.meta.game_time_seconds - 100.0).abs() < 1e-3);
        assert_eq!(out.meta.player_location_name, "{20004,1}");

        assert_eq!(out.overrides.get("sectoramacro").map(String::as_str), Some("argon"));
        assert_eq!(out.chunks.len(), 1);

        let chunk = &out.chunks[0];
        assert_eq!(chunk.sector_macro, "sectoramacro");
        let slice = &out.bytes[chunk.byte_range.clone()];
        assert!(slice.starts_with(b"<component class=\"sector\""));
        assert!(slice.ends_with(b"</component>"));
    }

    #[test]
    fn scan_finds_multiple_sectors_skips_non_sector_components() {
        let payload: &[u8] = br#"
<savegame>
  <info></info>
  <universe>
    <component class="cluster" macro="c1">
      <component class="sector" macro="MacroA" owner="argon">
        <component class="zone">
          <component class="ship_s" id="[0x1]"><offset><position x="1" y="0" z="0"/></offset></component>
        </component>
      </component>
      <component class="sector" macro="MacroB" owner="teladi">
        <component class="ship_m" id="[0x2]"><offset><position x="2" y="0" z="0"/></offset></component>
      </component>
    </component>
  </universe>
</savegame>"#;

        let (tx, rx) = std::sync::mpsc::sync_channel(8);
        tx.send(payload.to_vec()).unwrap();
        drop(tx);

        let out = run_scan(rx, "/tmp/x.xml.gz".into(), std::time::UNIX_EPOCH).unwrap();
        assert_eq!(out.chunks.len(), 2);
        assert_eq!(out.chunks[0].sector_macro, "macroa");
        assert_eq!(out.chunks[1].sector_macro, "macrob");
        assert_eq!(out.overrides.len(), 2);
    }

    #[test]
    fn scan_handles_input_split_into_many_small_chunks() {
        let payload: &[u8] = br#"
<savegame><info></info><universe>
  <component class="sector" macro="SectorMacro" owner="argon"><component class="ship_l" id="[0x9]"><offset><position x="1" y="0" z="0"/></offset></component></component>
</universe></savegame>"#;

        // Split into 17-byte chunks.
        let (tx, rx) = std::sync::mpsc::sync_channel(payload.len() / 17 + 2);
        for slice in payload.chunks(17) {
            tx.send(slice.to_vec()).unwrap();
        }
        drop(tx);

        let out = run_scan(rx, "/tmp/x".into(), std::time::UNIX_EPOCH).unwrap();
        assert_eq!(out.chunks.len(), 1);
        assert_eq!(out.chunks[0].sector_macro, "sectormacro");
        assert_eq!(out.overrides.get("sectormacro").map(String::as_str), Some("argon"));
    }
}
